Fix compilation errors when ARCH=riscv
When ARCH=riscv, the following compilation errors occur:

In file included from src/main.c:41:
src/codegen.c: In function ‘cfg_flatten’:
src/codegen.c:111:9: error: ‘flatten_ir’ undeclared (first use in this function); did you mean ‘fflatten_ir’?
  111 |         flatten_ir->src0 = fn->func->stack_size;
      |         ^~~~~~~~~~
      |         fflatten_ir
src/codegen.c:111:9: note: each undeclared identifier is reported only once for each function it appears in
src/codegen.c:110:19: warning: unused variable ‘fflatten_ir’ [-Wunused-variable]
  110 |         ph2_ir_t *fflatten_ir = add_ph2_ir(OP_define);
      |                   ^~~~~~~~~~~

Fix the erroneous variable name 'fflatten_ir' to 'flatten_ir' to avoid
compilation errors.

Fixes: 7f328f33a97d ("Apply editorial changes")